[tool.poetry]
name = "mole-hunting"
version = "1.0.0"
description = "This is Mole Hunting Game."
authors = ["sora81dev"]
license = "©2025 sora81dev"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"